### ISSUE TITLE
missing content for actual testing...

### ISSUE THREAD

**Issue by driven** [SketchUp/htmldialog-examples#1]
no icons for mac, so I made them using svg2pdf, shall I email them to you?

I added

```ruby
OSX = Sketchup.platform == :platform_osx
module TutorialController

  def self.create_step(index, title, &block)
    cmd = UI::Command.new(title, &block)
    cmd.tooltip = title
    ext = OSX ? 'pdf' : 'svg'
    # https://www.flaticon.com/free-icons/numbers_931
    icon = File.join(__dir__, 'images', "#{index}.#{ext}")
```
example 6:

missing semantic.min.js and semantic.min.css runtime error...

no material images shown or loaded...

john

**Comment by thomthom** [comment]
Ah! Doh! I forgot about that.
Email works fine, pull request is better ;)

**Comment by thomthom** [comment]
> missing semantic.min.js and semantic.min.css runtime error...

Oh - that's strange. It looks like it didn't upload the file. Almost as if it thought it was a sub-repo... Let me look into that one.

**Comment by thomthom** [comment]
Yea, Semantic UI was a sub-repo. So unless you recursively checked it out you'd not get the files. I changed it to just be regular bundled files.

**Comment by driven** [comment]
here are the pdf's and .svg's that work with the code above...
[images copy.zip](https://github.com/SketchUp/htmldialog-examples/files/1487564/images.copy.zip)

after many years I still haven't looked into making 'pull requests' :-o
